profiles/urls.py
from django.urls import path
from .views import user_login,signup,update_profile,get_profile, user_logout, ProfileDetailview, get_all_user

app_name="profiles"
urlpatterns=[
    path('login',user_login,name='login'),
    path('signup', signup, name='signup'),
    path('update-profile',update_profile, name='update-profile'),
    path('', get_profile, name='profile'),
    path('logout', user_logout,name='logout'),
    path("<int:pk>/profile", ProfileDetailview.as_view(), name="profile-detail"),
    path('peoples', get_all_user, name='peoples')

]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from post.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include("post.urls",namespace="post")),
    path('profiles/', include("profiles.urls", namespace="profiles")),
    path('',homepage, name='homepage'),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

# Create your models here.

STATUS_CHOICE=(
    ("send","send"),
    ("accepted", "accepted")
)



class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    address=models.CharField(max_length=100)
    bio=models.TextField(blank=True)
    profile_pic=models.ImageField(upload_to="profile",validators=[FileExtensionValidator(['png','jpg','jpeg'])])
    friends= models.ManyToManyField(User, blank=True, related_name="friends")

    def __str__(self):
        return f"{self.user.username} profile has been created "
    
    def full_name(self):
        return self.user.first_name + ' ' + self.user.last_name

    def email(self):
        return self.user.email

    def username(self):
        return self.user.username 
    
class Relationship(models.Model):
    sender= models.ForeignKey(Profile,on_delete=models.CASCADE,related_name="sender")
    receiver=models.ForeignKey(Profile, on_delete=models.CASCADE,related_name="receiver")
    status=models.CharField(max_length=8,choices=STATUS_CHOICE)

    def __str__(self):
        return f"{self.sender.user.username} has sent the request to {self.receiver.user.username}"
    

    

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
    username=forms.CharField(max_length=100,label="username")
    password=forms.CharField(max_length=100, label="password",widget=forms.PasswordInput())

class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username', 'first_name', 'last_name','email','password1','password2')

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('address','bio', 'profile_pic') 

    

profiles/views.py
from django.shortcuts import render,redirect
from .forms import LoginForm,SignupForm, UserUpdateForm
from django.contrib.auth import authenticate, login, logout
from .models import Profile
from django.contrib.auth.decorators import login_required
from post.models import Post
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def user_login(request):
    forms=LoginForm()
    if  request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('/')
    context={"form":forms}
    return render(request, 'profiles/login.html', context)

def signup(request):
    form=SignupForm()
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/profiles/login")
        
    context={"form":form}
    return render(request, "profiles/signup.html", context)

@login_required(login_url='/profiles/login')
def update_profile(request):
    profile=Profile.objects.get(user=request.user)
    forms= UserUpdateForm(instance=profile)
    if request.method=='POST':
        form=UserUpdateForm(request.POST,request.FILES, instance=profile)
        # print(form.is_valid())
        if form.is_valid():
            instance=form.save(commit=False)  
            instance.user=request.user    
            instance.save()
            return redirect ("/")
    context={"form":forms}
    return render(request, "profiles/update_profile.html", context)

@login_required(login_url='/profiles/login')
def get_profile(request):
    profile=Profile.objects.get(user=request.user)
    posts=Post.objects.filter(author=request.user)
    post_count=posts.count()
    context={"profile":profile, "posts":posts, "post_count":post_count}
    return render(request,"profiles/profile.html",context)


@login_required(login_url='/profiles/login')
def user_logout(request):
    logout(request)
    return redirect("/profiles/login")


class ProfileDetailview(LoginRequiredMixin,DetailView):
    model=Profile
    pk_url_kwarg= 'pk'
    template_name='profiles/profile.html'

@login_required(login_url='/profile/login')
def get_all_user(request):
    profiles = Profile.objects.exclude(user=request.user)
    context= {
        'profiles':profiles
    }
    return render(request, 'profiles/people-list.html',context) 

profiles/templates/profiles/login.html
{%extends 'base.html'%}
{% load django_bootstrap5 %}
{%block content%}
<h2>
    login
</h2>
<form method="post" >
    {%csrf_token%}
    {% bootstrap_form form %}
    
    <input value="login" type="submit" class="btn btn-primary">
    </form>
{%endblock%}

profiles/templates/profiles/people-list.html
{%extends "base.html"%}

{%block content%}
{%for profile in profiles%}

<div class="d-flex flex-start p-2">
    <img class="rounded-circle shadow-1-strong me-3" src="{{profile.profile_pic.url}}" alt="avatar" width="60"
        height="60" />
    <div>
        <a href="{%url 'profiles:profile-detail' profile.id%}" style="text-decoration: none; color: black;">
            <h6 class="fw-bold mb-1 mt-4">{{profile.user.username}}</h6>
        </a>
    </div>
</div>
 
{%endfor%}
{%endblock%}

profiles/templates/profiles/profile.html
{%extends 'base.html'%}
{%block content%}
<section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col-md-12 col-xl-4">
     
            <div class="card" style="border-radius: 15px;">
    <div class="card-body text-center">
    <div class="mt-3 mb-4">
    <img src="{{profile.profile_pic.url}}"
                    class="rounded-circle img-fluid" style="width: 100px;" />
    </div>
    <h4 class="mb-2">{{profile.full_name}}</h4>
    <p class="text-muted mb-4">{{profile.email}} <span class="mx-2">|</span> 
                    {{profile.address}}</p>
    <div class="mb-4 pb-2">
    <button type="button" class="btn btn-outline-primary btn-floating">
    <i class="fab fa-facebook-f fa-lg"></i>
    </button>
    <button type="button" class="btn btn-outline-primary btn-floating">
    <i class="fab fa-twitter fa-lg"></i>
    </button>
    <button type="button" class="btn btn-outline-primary btn-floating">
    <i class="fab fa-skype fa-lg"></i>
    </button>
    </div>
    {%if request.user == profile.user%}
    <a class="btn btn-primary" href="{%url 'profiles:update-profile'%}" role="button">update profile</a>
   {%endif%}
    <div class="d-flex justify-content-between text-center mt-5 mb-2">
    <div>
    <p class="mb-2 h5">{{post_count}}</p>
    <p class="text-muted mb-0">posts</p>
    </div>
    <div class="px-3">
    <p class="mb-2 h5">8512</p>
    <p class="text-muted mb-0">friends</p>
    </div>
    <div>
    <p class="mb-2 h5">4751</p>
    <p class="text-muted mb-0">comments</p>
    </div>
    </div>
    </div>
    </div>
     
          </div>
    </div>
    </div>
    </section>
{%endblock%}

profiles/templates/profiles/signup.html
{%extends 'base.html'%}
{% load django_bootstrap5 %}
{%block content%}
<h2>
    signup
</h2>
<form method="post" action="{%url 'profiles:signup'%}">
    {%csrf_token%}
    {% bootstrap_form form %}
    
    <input value="signup" type="submit" class="btn btn-primary">
    </form>
{%endblock%}

profiles/templates/profiles/update_profile.html
{%extends 'base.html'%}
{% load django_bootstrap5 %}
{%block content%}
<h2>
    update profile
</h2>
<form method="post" enctype="multipart/form-data" >
    {%csrf_token%}
    {% bootstrap_form form %}
    
    <input value="update profile" type="submit" class="btn btn-primary">
    </form>
{%endblock%}