post/urls.py
from django.urls import path
from .views import delete_post, update_post


app_name="post"

urlpatterns=[
    path("delete/<int:post_id>", delete_post, name="delete-post"),
    path("update/<int:post_id>", update_post, name="update-post")
]

profiles/urls.py
from django.urls import path
from .views import user_login,signup,update_profile,get_profile, user_logout, ProfileDetailview, get_all_user

app_name="profiles"
urlpatterns=[
    path('login',user_login,name='login'),
    path('signup', signup, name='signup'),
    path('update-profile',update_profile, name='update-profile'),
    path('', get_profile, name='profile'),
    path('logout', user_logout,name='logout'),
    path("<int:pk>/profile", ProfileDetailview.as_view(), name="profile-detail"),
    path('peoples', get_all_user, name='peoples')

]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from post.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include("post.urls",namespace="post")),
    path('profiles/', include("profiles.urls", namespace="profiles")),
    path('',homepage, name='homepage'),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>connectpeople</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <header>
      {%include 'navbar.html'%}
    </header>
    {%block content%}
    {%endblock%}
    <footer>
      <hr className="mt-5" />
      <footer style="text-align: center;">connectpeople &copy; Copyright 2023. All Rights Reserved.</footer>
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

templates/homepage.html
{%extends 'base.html'%}
{% load django_bootstrap5 %}
{%block content%}
<div class="row">
    <div class="col-md-8">
        <h4 class="m3">
            Recent Post
        </h4>
{%for post in posts%}
<div class="card m-3" style="width: 40rem;">
    {%if post.image%}
    <img src="{{post.image.url}}" class="card-img-top" alt="{{post.content}}">
    {%endif%}
    <div class="card-body">
     
      
      <div class="ms-5 d=flex">
        <h5 class="card-title">{{post.content}}</h5>
        {%if request.user == post.author%}
        <a class="btn btn-danger" href="{%url 'post:delete-post' post.id %}" role="button">delete</a>
        <a class="btn btn-secondary" href="{%url 'post:update-post' post.id%}" role="button">update</a>
        {%endif%}
    </div>
    <p class="card-text">{{post.author.username}}</p>

    <p>Comments ({{post.comment_set.count}}) </p>
        
    <form method="post" >
        {%csrf_token%}
        {% bootstrap_form c_form %}
        <input type="hidden" value="{{post.id}}" name="post_id">
        <input value="comment" name="comment_button" type="submit" class="btn btn-primary">
        </form> 
        {%for comment in post.get_all_comments%}
        <p>
            {{comment.comment}}
        </p>
        {%endfor%}
    </div>
  </div>
{%endfor%}
    </div>
    <div class="col-md-4">
      
        
     <form method="post" enctype="multipart/form-data" >
        {%csrf_token%}
        {% bootstrap_form form %}
        
        <input value="new post" name ="post_button" type="submit" class="btn btn-primary">
        </form> 
    </div>
</div>
{%endblock%}

templates/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <!-- Container wrapper -->
    <div class="container">
        <a class="navbar-brand text mb-1" href="/">connectpeople</a> 

        <!-- Toggle button -->
        <button class="navbar-toggler text-white" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarButtonsExample">
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="btn btn-secondary" href="{%url 'profiles:peoples'%}" role="button">people</a>
                </li>
            </ul>
            <!-- Left links -->
            
                <div class="d-flex">
                    
  {% if request.user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'profiles:profile'%}">
                    <img src="{{profile.profile_pic.url}}" alt="{{request.user.username}}" width="30"
                        class="rounded-pill">
                    <span>{{request.user.username}}</span>
                </a>
                <a href="{% url 'profiles:logout'%}" class="btn btn-danger ms-5" role="button"
                    aria-disabled="true">Logout</a>
                {%else%}
                <a href="{% url 'profiles:login'%}" class="btn btn-primary me-4" role="button"
                    aria-disabled="true">Login</a>
                {%endif%}
                </div>

            
                
                 
                
                
                 
            </ul>
        </div>
        <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->